# Generated by Django 5.0.4 on 2025-05-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomo6', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='category',
            field=models.CharField(default='Test', max_length=100),
            preserve_default=False,
        ),
    ]
