# Generated by Django 5.0.4 on 2025-05-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomo6', '0002_advertisement_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='category',
            field=models.CharField(choices=[('IT', 'IT'), ('HANDYMAN', 'HANDYMAN'), ('CLEANING', 'CLEANING'), ('CHILDCARE', 'CHILDCARE'), ('TUTORING', 'TUTORING'), ('TRANSPORTATION', 'TRANSPORTATION'), ('PET', 'PET'), ('OTHER', 'OTHER')], default='OTHER', max_length=100),
        ),
    ]
