# Generated by Django 5.0.4 on 2025-05-27 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pomo6', '0003_alter_advertisement_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advertisement',
        ),
    ]
