# Generated by Django 5.0.4 on 2025-08-02 17:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('profiles', '0001_initial'), ('profiles', '0002_alter_userprofile_image_alter_userprofile_user'), ('profiles', '0003_remove_userprofile_id_alter_userprofile_user'), ('profiles', '0004_alter_userprofile_image'), ('profiles', '0005_userprofile_first_name_userprofile_last_name')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(default=1, max_length=100)),
                ('last_name', models.CharField(default=1, max_length=100)),
            ],
        ),
    ]
