# Generated by Django 5.0.4 on 2025-08-05 07:43

import cloudinary.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])]),
        ),
    ]
