# Generated by Django 5.0.4 on 2025-08-02 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0024_order_thread_alter_order_description'),
        ('chat', '0001_squashed_0003_thread_advert_alter_message_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='advert',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='adverts.advertisement'),
            preserve_default=False,
        ),
    ]
