# Generated by Django 5.0.4 on 2025-08-02 17:07

import adverts.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('adverts', '0001_initial'), ('adverts', '0002_advertisement_user_order_ratings'), ('adverts', '0003_advertisement_image_alter_order_advertisement_and_more'), ('adverts', '0004_advertisement_fixed_price_and_more'), ('adverts', '0005_alter_advertisement_image'), ('adverts', '0006_remove_advertisement_views'), ('adverts', '0007_views'), ('adverts', '0008_alter_advertisement_image_ratingresponse'), ('adverts', '0009_alter_advertisement_options'), ('adverts', '0010_alter_advertisement_user'), ('adverts', '0011_alter_advertisement_image_alter_advertisement_slug'), ('adverts', '0012_advertisement_approved'), ('adverts', '0013_alter_views_advertisement'), ('adverts', '0014_order_created_on_alter_advertisement_image_and_more'), ('adverts', '0015_advertisement_archived'), ('adverts', '0016_remove_order_completed_order_accepted_on_and_more'), ('adverts', '0017_remove_order_created_on'), ('adverts', '0018_order_description'), ('adverts', '0019_order_thread'), ('adverts', '0020_alter_advertisement_category'), ('adverts', '0021_alter_advertisement_category'), ('adverts', '0022_alter_ratings_options_alter_order_status'), ('adverts', '0023_alter_order_status')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=2000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('IT', 'IT Help'), ('HANDYMAN', 'Handyman'), ('CLEANING', 'Cleaning'), ('CHILDCARE', 'Childcare'), ('TUTORING', 'Tutoring'), ('PET', 'Pet care')], max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to=settings.AUTH_USER_MODEL)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])])),
                ('fixed_price', models.FloatField(blank=True, null=True)),
                ('is_fixed_price', models.BooleanField(default=True)),
                ('max_price', models.FloatField(blank=True, null=True)),
                ('min_price', models.FloatField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
            ],
            options={
                'permissions': [('approve_listing', 'Can approve listing')],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='adverts.advertisement')),
                ('accepted_on', models.DateField(blank=True, null=True)),
                ('amount', models.FloatField(default=0)),
                ('completed_on', models.DateField(blank=True, null=True)),
                ('last_modified', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='CREATED', max_length=20)),
                ('description', models.TextField(default=1, max_length=2000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, validators=[adverts.validators.RatingValidator('The rating must be between 0 and 5')])),
                ('comment', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='adverts.order')),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'Ratings',
            },
        ),
        migrations.CreateModel(
            name='RatingResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('to_rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='adverts.ratings')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Views',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_date', models.DateTimeField(auto_now_add=True)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='adverts.advertisement')),
            ],
        ),
    ]
