# Generated by Django 5.0.4 on 2025-05-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=2000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('IT', 'IT Help'), ('HANDYMAN', 'Handyman'), ('CLEANING', 'Cleaning'), ('CHILDCARE', 'Childcare'), ('TUTORING', 'Tutoring'), ('TRANSPORTATION', 'Transportation'), ('PET', 'Pet care'), ('OTHER', 'Other')], default='OTHER', max_length=100)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
    ]
