# Generated by Django 5.0.4 on 2025-08-02 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('search_indexing', '0001_initial'), ('search_indexing', '0002_rename_body_tfidf_searchindex_body_idf_and_more'), ('search_indexing', '0003_rename_body_idf_searchindex_idf_and_more'), ('search_indexing', '0004_searchindex_body_tfidf_searchindex_title_tfidf')]

    initial = True

    dependencies = [
        ('adverts', '0023_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('title_tf', models.FloatField()),
                ('body_tf', models.FloatField()),
                ('idf', models.FloatField(blank=True, null=True)),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adverts.advertisement')),
                ('body_tfidf', models.FloatField(blank=True, null=True)),
                ('title_tfidf', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
